from __future__ import annotations

from .apply import (
    adopt_claude_symlink,
    classify,
    claude_symlink_adoption_needed,
    copy_paths,
    prompt_for_claude_symlink_adoption,
)
from .blocks import (
    append_patch_text,
    block_content_matches,
    block_managed_state,
    comparison_block_content,
    find_raven_block,
    guided_merge_instructions,
    normalized_block_content,
    raven_block_begin_for,
    raven_block_is_unchanged,
    raven_block_sha256,
    raven_managed_block,
    template_entry_text,
    update_raven_block,
    write_guided_merge_artifacts,
)
from .cli import (
    _parse_install_language,
    _run,
    cmd_init,
    cmd_install,
    cmd_upgrade,
    list_language_templates,
    main,
    select_language_interactively,
)
from .config import (
    _update_config_platform,
    build_config,
    component_disabled,
    config_excluded,
    default_config_text,
    load_config,
    parse_simple_toml,
    parse_value,
    path_matches,
    path_within,
    platform_excluded,
    replace_platform_line,
    strip_comment,
)
from .constants import (
    CLAUDE_BACKUP_PATH,
    CLAUDE_COMPONENT_PATHS,
    CLAUDE_PATH,
    CODEX_COMPONENT_PATHS,
    COMPONENT_PATHS,
    CONFIG_PATH,
    DEFAULT_CLAUDE_COMPONENTS,
    DEFAULT_CODEX_COMPONENTS,
    DEFAULT_COMPONENTS,
    DEFAULT_EXCLUDES,
    EXCLUDED_NAMES,
    KIND_FILE,
    KIND_SYMLINK,
    MANIFEST_PATH,
    MERGE_DIR,
    NON_TEMPLATE_DIRS,
    RAVEN_BLOCK_BEGIN,
    RAVEN_BLOCK_BEGIN_RE,
    RAVEN_BLOCK_END,
    REPO_ROOT,
    ROOT_INSTRUCTION_FILES,
    STARTER_TOOL_CONFIG_PATHS,
    _any_exists,
)
from .git_hooks import install_git_hooks
from .hashing import (
    destination_fingerprint,
    entry_fingerprint,
    file_sha256,
    same_content,
    sha256_bytes,
)
from .manifest import (
    git_ref,
    load_manifest,
    manifest_allows_upgrade,
    save_manifest,
    update_manifest,
)
from .models import ApplyPlan, Classification, RavenBlock, RavenConfig, TemplateEntry
from .plan import (
    apply_plan,
    build_apply_plan,
    claude_symlink_conflict,
    normalize_override,
    print_apply_summary,
    print_dry_run_plan,
    print_dry_run_summary,
    print_section,
)
from .template import (
    entries_for_destination,
    is_excluded,
    iter_template_entries,
    should_preserve_symlink,
)

__all__ = [
    # constants
    "REPO_ROOT",
    "DEFAULT_EXCLUDES",
    "EXCLUDED_NAMES",
    "CONFIG_PATH",
    "MANIFEST_PATH",
    "MERGE_DIR",
    "ROOT_INSTRUCTION_FILES",
    "CLAUDE_PATH",
    "CLAUDE_BACKUP_PATH",
    "RAVEN_BLOCK_BEGIN",
    "RAVEN_BLOCK_BEGIN_RE",
    "RAVEN_BLOCK_END",
    "DEFAULT_COMPONENTS",
    "DEFAULT_CLAUDE_COMPONENTS",
    "DEFAULT_CODEX_COMPONENTS",
    "COMPONENT_PATHS",
    "STARTER_TOOL_CONFIG_PATHS",
    "CLAUDE_COMPONENT_PATHS",
    "CODEX_COMPONENT_PATHS",
    "NON_TEMPLATE_DIRS",
    "KIND_FILE",
    "KIND_SYMLINK",
    "_any_exists",
    # models
    "TemplateEntry",
    "RavenConfig",
    "RavenBlock",
    "Classification",
    "ApplyPlan",
    # config
    "strip_comment",
    "parse_value",
    "parse_simple_toml",
    "build_config",
    "load_config",
    "default_config_text",
    "path_matches",
    "path_within",
    "component_disabled",
    "config_excluded",
    "platform_excluded",
    "replace_platform_line",
    "_update_config_platform",
    # template
    "is_excluded",
    "should_preserve_symlink",
    "iter_template_entries",
    "entries_for_destination",
    # hashing
    "sha256_bytes",
    "file_sha256",
    "entry_fingerprint",
    "destination_fingerprint",
    "same_content",
    # blocks
    "normalized_block_content",
    "comparison_block_content",
    "block_content_matches",
    "raven_block_sha256",
    "raven_block_begin_for",
    "raven_managed_block",
    "find_raven_block",
    "raven_block_is_unchanged",
    "block_managed_state",
    "update_raven_block",
    "template_entry_text",
    "append_patch_text",
    "guided_merge_instructions",
    "write_guided_merge_artifacts",
    # manifest
    "load_manifest",
    "git_ref",
    "save_manifest",
    "update_manifest",
    "manifest_allows_upgrade",
    # apply
    "classify",
    "copy_paths",
    "claude_symlink_adoption_needed",
    "adopt_claude_symlink",
    "prompt_for_claude_symlink_adoption",
    # plan
    "print_section",
    "print_apply_summary",
    "print_dry_run_summary",
    "build_apply_plan",
    "claude_symlink_conflict",
    "print_dry_run_plan",
    "apply_plan",
    "normalize_override",
    # git_hooks
    "install_git_hooks",
    # cli
    "_parse_install_language",
    "_run",
    "list_language_templates",
    "select_language_interactively",
    "cmd_init",
    "cmd_install",
    "cmd_upgrade",
    "main",
]
